<?php

/**
 * @file
 * ubl_show_persistent_url module.
 *
 *
 *  Copyright 2017 Leiden University Library
 *
 *  This file is part of ubl_show_persistent_url.
 *
 *  ubl_show_persistent_url is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/**
 * Implements hook_detail_tools_block_view().
 */
function ubl_show_persistent_url_detail_tools_block_view() {
  $block = array();

  if (arg(1) == 'object' && islandora_is_valid_pid(arg(2))) {
    $obj = islandora_object_load(arg(2));
    drupal_add_css(drupal_get_path('module', 'ubl_show_persistent_url') . '/css/ubl_show_persistent_url.css');
    drupal_add_js(drupal_get_path('module', 'ubl_show_persistent_url') . '/js/ubl_show_persistent_url.js');

    $url = ubl_show_persistent_url_get_persistent_url($obj);

    $additional = '<DIV class="link-additional">';
    $additional .= '<DIV class="menu">';
    $additional .= '<H3>Link</H3>';
    $additional .= '<DIV class="explain">';
    $additional .= t('Use the URL below to link to this item:');
    $additional .= '</DIV>';
    $additional .= '<INPUT type="text" value="'.$url.'" id="persistenturl"/>';
    $additional .= '</DIV>';
    $additional .= '</DIV>';

    // Put this in a item list.
    $block['list'] = array(
      '#type' => 'ul',
      '#attributes' => array('class' => array('dc-detail-tools', 'ubl-detail-tools')),
      '#items' => array(
        array(
          'data' => l(
                      '<span>link</span><i class="fa fa-link" aria-hidden="true"></i>',
                      $url,
                      array('attributes' => array('title' => 'link'),'html' => TRUE)
                     ),
        ),
      ),
      '#theme' => 'item_list',
    );
    $block['linkadditional'] = array(
      '#type' => 'markup',
      '#markup' => $additional,
    );

/*
    $menu = array();

    $menu['class'] = 'ubl-detail-tools';
    $buttons = array();

    $additional = '';

    $url = ubl_show_persistent_url_get_persistent_url($obj);
    $buttons['link'] = array(
      'label' => 'link',
      'class' => 'fa-link',
      'url' => $url,
      'additional' => $additional,
    );

    $menu['buttons'] = $buttons;

    $block['content']['#markup'] = theme('ubl_detail_tools', $menu);
*/
  }
  return $block;
}

function ubl_show_persistent_url_get_persistent_url($object) {
  $url = '';
  if ($object) {
    if (module_exists("islandora_handle")) {
      if (isset($object['MODS'])) {
        $xpath = "/mods:mods/mods:identifier[@type='hdl']";
        $content = $object['MODS']->content;
        $domdoc = new DOMDocument();
        if ($domdoc->loadXML($content)) {
          $domxpath = new DOMXPath($domdoc);
          $domxpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
          $domnodelist = $domxpath->query($xpath);
          if ($domnodelist->length > 0) {
            foreach ($domnodelist as $domnode) {
              $text = $domnode->textContent;
              if (isset($text) && strlen($text) > 0) {
                $url = $text;
                break;
              }
            }
          }
        }
      }
    }
    if (strlen($url) == 0) {
      $url = url("islandora/object/" . $object->id, array('absolute' => TRUE));
    }
  }
  return $url;
}
